language: node_js
node_js:
  - "7"

script:
  - npm install
  - mkdir artifacts
  - |
    GIT_DESCRIBE=$(git describe)
    sed -i -e "s/%GIT_DESCRIBE%/$(git describe)/g" index.html
    tar -czf artifacts/nimrod-portal-${GIT_DESCRIBE}.tar.gz \
      --transform "s/^\./nimrod-portal-${GIT_DESCRIBE}/" \
      --exclude=./artifacts \
      --exclude=./.git \
      .

install: true
deploy:
  provider: releases
  api_key:
    secure: gSIKD0EVDLmfzkbn6HzGpOyHbUBekyYbMSh/xLeuo6B9ywnl57GY0WcTziaky9GypXzVMb7IcpNeTYsaKGDpuQoQ+o2Nke/u3J/oGeasvFwIVEnaLd1B2mrwB1EL81LLS5P0ngJwxF9CNvSc5L0GMRgCL1bqkMjBAKtq9fgRvLv/J/I5ACsr+JOVj1PUCVMp6N59AkDySXP8lCGTou09zq54K2Cget1RchTE4oekOfWV5X2OGHnXBmKlCGayKb0Bmi5RjlfRxfECC/UHjo7jd92WjXXyvYBLCzPqfWuz4gM6VW+pvYHLfo/wEmMCPsdKAWxyryCotjbwS1AnqDo0So4BGQXtxtT29dgpB04RfLNjvBOBrQZ7Yu8rbu4xAd1MgnlJhzoEmaJioMtY4Mrs4gVUjjnKnuJKFJpX6FsV+zFWiqQMoslF0sQ8wKgtGn8f7TmDi89MKzFvvFOemkPges8JTGegJtVU34Sns3iVyP1RJskwE56YAiEcDnYo3Qe1luJirAhpOjZ/RikjQz76xX3+7fbEJ82eCLn/+tcWJ+euiBdRsRHCR6gPeBrG7k1d/6U7kzPvHQnOJSLi2lJ2GjVldSj2ER5h8biVEmWAIq1k07Cea8eZLv5KYaD+hPIIjCmec6JxF99zKGqTuOx3xiBJfcqyyPJNut2RvzzuUwo=
  skip_cleanup: true
  file_glob: true
  file: artifacts/nimrod-portal-*.tar.gz
  draft: false
  overwrite: true
  on:
    tags: true
